# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('wallet_number', models.CharField(max_length=100)),
                ('bitcoin_amount', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('finished', models.BooleanField(default=False)),
                ('winner', models.BooleanField(default=False)),
                ('test', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameCard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('selected', models.BooleanField(default=False)),
                ('prize', models.BooleanField(default=False)),
                ('reveal', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='montyhall.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
