# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wallet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposit_id', models.CharField(default=wallet.models.uuid_str, max_length=100, primary_key=True, serialize=False)),
                ('from_wallet', models.CharField(max_length=100)),
                ('bitcoin_amount', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('spent', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='deposit',
            name='to_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wallet.Wallet'),
        ),
    ]
