# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-21 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount_out', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('fee', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('from_wallet', models.CharField(max_length=100)),
                ('spent', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='to_wallet',
        ),
        migrations.AddField(
            model_name='wallet',
            name='label',
            field=models.CharField(default='TEMP', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wallet.Wallet'),
        ),
    ]
